#!/usr/bin/ash

run_hook() {
   if bcachefs unlock -c $root >/dev/null 2>&1; then
        echo "Unlocking $root:"

        while true; do
            bcachefs unlock $root && break
        done
    fi

    echo "Running fsck on $root:"
    bcachefs fsck $root
}

# vim: set ft=sh ts=4 sw=4 et:
